#!/bin/sh
TAUROOT=/share/apps/tau
MACHINE=x86_64
LIBDIR=${TAUROOT}/${MACHINE}/lib

java -Xmx500m -cp ${LIBDIR}/TauIL.jar:${LIBDIR}/ParaProf.jar:${LIBDIR}/ParaProf-Old.jar:${LIBDIR}/java_cup.jar:${LIBDIR}/perfdmf.jar TauIL.Tool $@
